
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK
    display_name: Gov.UK - Dev
    output_directory: build_output
    project: GovUK.xcodeproj
    bundle_identifier: uk.gov.govuk
    profile_specifiers:
      uk.gov.govuk: "match AppStore uk.gov.govuk"
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.1)
  match: &MATCH_DEFAULTS
    method: "adhoc"
  deliver: &DELIVER_DEFAULTS
    groups: 
      - GOV.UK APP
      - GOV.UK OTHER

unit:
  <<: *DEFAULTS

alpha:
  <<: *DEFAULTS
  app:
    <<: *APP_DEFAULTS
    display_name: Gov.UK - Alpha
  match:
    <<: *MATCH_DEFAULTS
    method: "appstore"