
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK
    output_directory: build_output
    project: GovUK.xcodeproj
    bundle_identifier: uk.gov.govuk
    profile_specifiers:
      uk.gov.govuk: "match AppStore uk.gov.govuk"
      uk.gov.govuk.notification-service: "match AppStore uk.gov.govuk.notification-service"
    export_method: app-store
    build_configuration: Release
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.2)
  match: &MATCH_DEFAULTS
    method: "adhoc"
  deliver: &DELIVER_DEFAULTS
    groups: 
      - GOV.UK APP
      - GOV.UK OTHER

unit:
  <<: *DEFAULTS
  app:
    <<: *APP_DEFAULTS
    scheme: GovUKDev
    build_configuration: Debug

alpha:
  <<: *DEFAULTS
  app:
    <<: *APP_DEFAULTS
    scheme: GovUKAlpha
    bundle_identifier: uk.gov.govuk.dev
    profile_specifiers:
      uk.gov.govuk.dev: "match AdHoc uk.gov.govuk.dev"
      uk.gov.govuk.dev.notification-service: "match AdHoc uk.gov.govuk.dev.notification-service"
    firebase_app_id: 1:299196369979:ios:d118523927e181c1e3e01e
    export_method: ad-hoc
    build_configuration: Alpha
  match:
    <<: *MATCH_DEFAULTS

beta:
  <<: *DEFAULTS
  app:
    <<: *APP_DEFAULTS
    build_configuration: Release
  match:
    <<: *MATCH_DEFAULTS
    method: "appstore"