
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK
    output_directory: build_output
    project: GovUK.xcodeproj
    bundle_identifier: uk.gov.govuk.dev
    profile_specifiers:
      uk.gov.govuk.dev: "match AdHoc uk.gov.govuk.dev"
      uk.gov.govuk.dev.notification-service: "match AdHoc uk.gov.govuk.dev.notification-service"
    export_method: ad-hoc
    build_configuration: Debug
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.6)
  match: &MATCH_DEFAULTS
    method: "adhoc"
  deliver: &DELIVER_DEFAULTS
    groups:
      - GOV.UK APP

unit:
  <<: *DEFAULTS
  app:
    <<: *APP_DEFAULTS

alpha:
  <<: *DEFAULTS
  app:
    <<: *APP_DEFAULTS
    build_configuration: Release
  match:
    <<: *MATCH_DEFAULTS

beta:
  <<: *DEFAULTS
  app:
    <<: *APP_DEFAULTS
    bundle_identifier: uk.gov.govuk
    profile_specifiers:
      uk.gov.govuk: "match AppStore uk.gov.govuk"
      uk.gov.govuk.notification-service: "match AppStore uk.gov.govuk.notification-service"
    export_method: app-store
    build_configuration: Release
  match:
    <<: *MATCH_DEFAULTS
    method: "appstore"
