
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK
    display_name: GovUK - Dev
    output_directory: build_output
  scan:
    devices:
      - iPhone 15 Pro

unit:
  <<: *DEFAULTS

alpha:
  app:
    <<: *APP_DEFAULTS
    display_name: GovUK - Alpha
