
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK
    display_name: Gov.UK - Dev
    output_directory: build_output
    project: GovUK.xcodeproj
    workspace: GovUK.xcworkspace
    bundle_identifier: uk.gov.govuk
    profile_specifiers:
      uk.gov.govuk: "match AppStore uk.gov.govuk"
  scan:
    devices:
      - iPhone 16 Pro
  match: &MATCH_DEFAULTS
    method: "adhoc"

unit:
  <<: *DEFAULTS

alpha:
  app:
    <<: *APP_DEFAULTS
    display_name: Gov.UK - Alpha
  match:
    <<: *MATCH_DEFAULTS
    method: "appstore"