name: Beta

on:
  workflow_call:
  push:
    branches:
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-beta
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  unit-test:
    uses: ./.github/workflows/unit_test.yml
  sonar-scan:
    uses: ./.github/workflows/sonar_scan_branch.yml
    needs: unit-test
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy:
    name: Deploy
    needs: sonar-scan
    runs-on: macos-15
    environment: Beta

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # pin@v4.1.5
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # pin@v1.202.0
        with:
          bundler-cache: true

      - name: Select xcode
        run: xcodes select

      - name: Deploy
        run: bundle exec fastlane beta
        env:
          APP_STORE_KEY_CONTENT: ${{ secrets.APP_STORE_KEY_CONTENT }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_KEY_ISSUER_ID: ${{ secrets.APP_STORE_KEY_ISSUER_ID }}
          MATCH_CERTIFICATE_TOKEN: ${{ secrets.MATCH_CERTIFICATE_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ONESIGNAL_APP_ID: ${{ vars.ONESIGNAL_APP_ID }}

      - name: Save Artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # pin@v4.3.3
        with:
          name: build-output
          path: build_output