name: Beta

on:
  workflow_call:
  push:
    branches:
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-beta
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  unit-test:
    uses: ./.github/workflows/unit_test.yml
  sonar-scan:
    uses: ./.github/workflows/sonar_scan_branch.yml
    needs: unit-test
    secrets:
      BW_ACCESS_TOKEN: ${{ secrets.BW_ACCESS_TOKEN }}
  deploy:
    name: Deploy
    needs: sonar-scan
    runs-on: macos-15
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # pin@v4.1.5
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # pin@v1.245.0
        with:
          bundler-cache: true

      - name: Get Secrets
        uses: bitwarden/sm-action@14f92f1d294ae3c2b6a3845d389cd2c318b0dfd8 # pin@v2.2.0
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          base_url: https://vault.bitwarden.eu
          secrets: |
            4d6340bc-d8c4-4449-9c9c-b32500f0f282 > MATCH_PASSWORD
            9de05f7b-cdfe-485d-86a6-b32a00af5922 > MATCH_CERTIFICATE_TOKEN
            0aed09d2-d4f7-4432-a099-b32a00e0521b > APP_STORE_KEY_ISSUER_ID
            ba8cdcd5-7bbd-437e-bfc9-b32a00e07df8 > APP_STORE_KEY_ID
            d0bc8f38-8ebe-4b1d-9e55-b32a00e1b064 > APP_STORE_KEY_CONTENT

      - name: Select xcode
        run: xcodes select

      - name: Deploy
        run: bundle exec fastlane beta
        env:
          BASE_URL: ${{ vars.BASE_URL }}
          ONESIGNAL_APP_ID: ${{ vars.ONESIGNAL_APP_ID }}
          ASSETCATALOG_COMPILER_APPICON_NAME: ${{ vars.ASSETCATALOG_COMPILER_APPICON_NAME }}
          AUTHENTICATION_BASE_URL: ${{ vars.AUTHENTICATION_BASE_URL }}
          AUTHENTICATION_CLIENT_ID: ${{ vars.AUTHENTICATION_CLIENT_ID }}
          CHAT_BASE_URL: ${{ vars.CHAT_BASE_URL }}
          TOKEN_BASE_URL: ${{ vars.TOKEN_BASE_URL }}
          GOOGLE_SERVICES_FILE: ${{ vars.GOOGLE_SERVICES_FILE }}

      - name: Save Artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # pin@v4.3.3
        with:
          name: build-output
          path: build_output