name: Deploy Test

on:
  push:
    branches:
      - deploy-testflight-builds

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # pin@v4.1.5
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@82dd21cb955e5633e70976c289b2e3b01c0f18db # pin@v1.176.0
        with:
          bundler-cache: true

      - name: Select xcode
        run: xcodes select

      - name: Deploy
        run: bundle exec fastlane alpha
        env:
          APP_STORE_KEY_CONTENT: ${{ secrets.APP_STORE_KEY_CONTENT }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_KEY_ISSUER_ID: ${{ secrets.APP_STORE_KEY_ISSUER_ID }}
          APP_STORE_USERNAME: ${{ secrets.APP_STORE_USERNAME }}
          MATCH_CERTIFICATE_TOKEN: ${{ secrets.MATCH_CERTIFICATE_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}