name: Unit Test

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unit
  cancel-in-progress: true

jobs:
  build:
    name: Unit test
    runs-on: macos-15
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # pin@v4.1.5
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # pin@v1.245.0
        with:
          bundler-cache: true

      - name: Select xcode
        run: xcodes select

      - name: Unit tests
        run: bundle exec fastlane unit

      - name: Archive failure diffs
        if: failure()
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # pin@v4.3.3
        with:
          name: FailureDiffs
          path: FailureDiffs
          retention-days: 1

      - name: Save code coverage results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # pin@v4.3.3
        with:
          name: test-output
          path: test_output